name: 'Setup Project'
description: 'Checkouts repo, sets up bun and installs dependencies'
runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install Dependencies
      shell: bash
      run: bun ci

    - name: Build Packages
      shell: bash
      run: bun run build
